[package]
name = "avformat"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags ={ workspace = true }
avcodec = { workspace = true }

[[bin]]
name = "wav_example"
path = "examples/wav_example.rs"
