[workspace]
resolver = "2"

members = [ 
    "packages/ffav", 
    "packages/avformat",
    "packages/avcodec",
    "packages/avutil", 
]

[workspace.dependencies]
ffav = { path = "packages/ffav" }
avformat = { path = "packages/avformat" }
avcodec = { path = "packages/avcodec" }
avutil = { path = "packages/avutil" }

bitflags = "2.9.1"
strum = "0.27"
strum_macros = "0.27"

