[package]
name = "ffav-types"
version = "0.1.0"
edition = "2024"

[dependencies]
strum ={ workspace = true }
strum_macros = { workspace = true }
bytes = { workspace = true }
arc-slice = { workspace = true, features = ["inlined", "abort-on-refcount-overflow"]}
bitflags = { workspace = true }
env_logger ={ workspace = true }
thiserror = { workspace = true }
