[package]
name = "ffav-format"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags ={ workspace = true }
ffav-codec = { workspace = true }
ffav-types ={ workspace = true }

[[bin]]
name = "wav_example"
path = "examples/wav_example.rs"
