[package]
name = "ffav"
version = "0.1.0"
edition = "2024"

[dependencies]
ffav-format = { path = "../ffav-format" }
ffav-codec = { path = "../ffav-codec" }
ffav-util = { path = "../ffav-util" }
ffav-types = { path = "../ffav-types" }
