[package]
name = "ffav"
version = "0.1.0"
edition = "2024"

[dependencies]
ffav-format ={ workspace = true  }
ffav-codec = { workspace = true }
ffav-util = { workspace = true }
ffav-types = { workspace = true }

[[bin]]
name = "ffav"
path = "src/bin/ffav.rs"
