[package]
name = "ffav"
version = "0.1.0"
edition = "2024"

[dependencies]
ffav-pipeline ={ workspace = true  }
ffav-decode = { workspace = true }
ffav-util = { workspace = true }
ffav-types = { workspace = true }

# clap = { workspace = true, features = ["derive"] }

[[bin]]
name = "ffav"
path = "src/bin/ffav.rs"
