[package]
name = "ffav-demux"
version = "0.1.0"
edition = "2024"

[dependencies]
ffav-types = { workspace = true }
ffav-utils = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
inventory = { workspace = true }

[[bin]]
name = "wav_example"
path = "examples/wav_example.rs"